export const LOADING = "LOADING";
export const FETCH_MAIN_CATEGORY = "FETCH_MAIN_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_SUB_CATEGORY = "FETCH_SUB_CATEGORY";
export const ADD_CATEGORY = "BANK_DETAILS";
export const ADD_SUB_CATEGORY = "PASSWORD";
export const ADD_MAIN_CATEGORY = "USER_NAME";
export const CATEGORY_ERROR = "ADMIN_ERROR";
