export const PAYMENT_LOADING = "LOADING";
export const ALL_CANCELLED_ORDERS = "ALL_CANCELLED_ORDERS";
export const ALL_SHIPPED_ORDERS = "ALL_SHIPPED_ORDERS";
export const PAY_SELLER = "PAY_SELLER";
export const REFUND_USER = "REFUND_USER";
export const PAYMENT_ERROR = "PAYMENT_ERROR";