export const VIEW_SELLER_ORDER = "VIEW_SELLER_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";
export const SHIPPED_THE_ORDER = "SHIPPED_THE_ORDER";
export const VIEW_SHIPPED_ORDERS = "VIEW_SHIPPED_ORDERS";
export const REMOVE_SELLER_ORDER = "REMOVE_SELLER_ORDER";
export const SELLER_ORDER_ERROR = "SELLER_ORDER_ERROR";