export const PRODUCT_PRE_LOADING = "PRODUCT_PRE_LOADING";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const PRODUCTS_BY_CATEGORY = "PRODUCTS_BY_CATEGORY";
export const PRODUCTS_BY_SUBCATEGORY = "PRODUCTS_BY_SUBCATEGORY";
export const USER_PRODUCT_ERROR = "USER_PRODUCT_ERROR";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const LATEST_PRODUCTS = "LATEST_PRODUCTS";
