export const FETCH_SELLER_ALL_PRODUCTS = "FETCH_SELLER_ALL_PRODUCTS";
export const SELLER_PRODUCT_ERROR = "SELLER_PRODUCT_ERROR";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_MAIN_CATEGORY = "FETCH_MAIN_CATEGORY";
export const LOADING = "LOADING";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";