import React from "react";
import "./conditionOfUse.css";
const ConditionOfUse = () =>{
    return (
        <div className="container">
            <div className="condition-of-use">
                <div className="content-of-condition-of-use">
                <h6>amYflip Condition of Use</h6>
                <br/>
                <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules
                     there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000.
                     This electronic record is generated by a computer system and does not require any physical 
                     or digital signatures.
                    <br/><br/>
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing 
                    the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.amYflip.com][www.amYflip.com] (“Website”), including the 
                    related mobile site and mobile application (hereinafter referred to as “Platform”)</p>
                </div>
           
            </div>
        </div>
       
    )
}
export default ConditionOfUse;